docs/modules/ROOT/pages/discover/index.adoc
Purpose: The purpose of this PR is to close [HACDOCS-911](https://issues.redhat.com/browse/HACDOCS-911)
=> Why Konflux?

docs/modules/ROOT/pages/discover/slsa-conformity.adoc
Copying the SLSA conformity doc published for AppStudio.
The only update is the xref at the very end of the doc.
=> Adding SLSA conformity

docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc
This is a copy of the AppStudio guide https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/proc_multiversion/
=> Managing multiple software versions

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Add some more options for the SCM secrets lookup in bild service.
=> Add more Build service secrets lookup options

docs/modules/ROOT/pages/how-tos/testing/build/index.adoc, docs/modules/ROOT/pages/how-tos/testing/build/snyk.adoc
Purpose: The purpose of this PR is to review and update build time tests content. I have copied and updated the AppStudio content. Next tasks is to review and update it.
=> Updated build time tests

docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec.adoc
As requested in [HACDOCS-959](https://issues.redhat.com/browse/HACDOCS-959):
- Removed an acronym from the title
- Linked to the https://konflux-ci.dev/docs/how-tos/testing/integration/adding/
- Removed procedures
- Kept the additional resources section
=> Managing compliance with EC

docs/modules/ROOT/pages/index.adoc
If you have time for it--I'm trying to update the SLSA overview doc as well, to make it accurate
=> Update attestation/provenance definition

docs/modules/ROOT/pages/advanced-how-tos/managing-security-fix.adoc
Mostly a copy of the AppStudio guide.
Rewrote the part about user access.
Updated or removed links.
Left several comments in places where more links might be added in the future.
Updates were initially discussed in: https://docs.google.com/document/d/1YhIYiOdcLAvq0Gs7ae2madgPbk0Y7gmTCtW8Nd5boag
=> Managing a security fix

docs/modules/ROOT/pages/how-tos/testing/index.adoc
=> how-tos/testing: fix spelling error

docs/modules/ROOT/pages/advanced-how-tos/installing/index.adoc
Jira: https://issues.redhat.com/browse/HACDOCS-958
=> Updated the install Konflux content

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/testing/index.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/creatingoverridesnapshot.adoc
* add procedure to create override snapshot
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
=> feat(STONEINTG-892): add proc to create override snapshot

docs/modules/ROOT/pages/how-tos/testing/integration/creatingoverridesnapshot.adoc
* update doc to add snapshotComponent's source for override snapshot
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
=> feat(STONEINTG-892): update doc for override snapshot

docs/modules/ROOT/pages/getting-started/cli.adoc
Update cli.adoc based on suggestion in https://github.com/konflux-ci/docs/pull/29
=> Update cli.adoc based on suggestion in https://github.com/konflux-ci/docs/pull/29

docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
Update timestamps to reflect use of RFC3339 formatting.
=> feat(STONEINTG-659): update docs to usage of RFC3339 timestamp

docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
[STONEBLD-2506](https://issues.redhat.com/browse/STONEBLD-2506)
=> Document support for custom pip index servers

docs/modules/ROOT/pages/advanced-how-tos/_nav.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan-admission.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/index.adoc
~I plan to add a migration of the FBC documentation to this PR as well.~ I have opened a new PR for that instead: #86 .
=> Migrate and update basic release documentation

docs/modules/ROOT/pages/how-tos/testing/integration/adding.adoc
Connect adding and creating custom integration test pages.
=> Connect adding and custom creation of integration test pages

docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec.adoc, docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc, docs/modules/ROOT/pages/advanced-how-tos/managing-security-fix.adoc, docs/modules/ROOT/pages/how-tos/configuring/configuration-as-code.adoc, docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc, docs/modules/ROOT/pages/how-tos/configuring/customizing-the-build.adoc, docs/modules/ROOT/pages/how-tos/configuring/hermetic-builds.adoc, docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc, docs/modules/ROOT/pages/how-tos/creating.adoc, docs/modules/ROOT/pages/how-tos/deleting.adoc, docs/modules/ROOT/pages/how-tos/testing/build/index.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/creatingoverridesnapshot.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/rerunning.adoc, docs/modules/ROOT/pages/index.adoc
Including use of the {ProductName} and xrefs instead of raw HTML links.
=> Clean up references

docs/modules/ROOT/pages/advanced-how-tos/installing/enabling-builds.adoc, docs/modules/ROOT/pages/how-tos/creating.adoc
Jira: [KFLUXBUGS-805](https://issues.redhat.com/browse/KFLUXBUGS-805)
Add info about `/ok-to-test` to relevant places where the user could come across problems with permissions
=> add info about permissions to run PipelineRuns and /ok-to-test

docs/antora.yml, docs/modules/ROOT/pages/troubleshooting/_nav.adoc, docs/modules/ROOT/pages/troubleshooting/index.adoc
One entry so far: "No space left on device"
=> Add Troubleshooting docs

docs/modules/ROOT/pages/troubleshooting/index.adoc
This commit adds potential troubleshooting for pipelineRun timeouts and a potential fix.
=> Add troubleshooting for PipelineRun timeout

docs/modules/ROOT/pages/advanced-how-tos/_nav.adoc, docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec/customizing-policy.adoc, docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec/index.adoc, docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec/policy-evaluations.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan-admission.adoc, docs/modules/ROOT/pages/how-tos/metadata/index.adoc
=> Add docs on how to use a custom EC policy

docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc
Update the doc to include all the updates made to the
`project-controller` recently as well as lessons learned from having
users  try it out.
In particular, this update includes instructions for users to create
`ImageRepository`resources for thier components. This therefore,
consists of a solution to KFLUXBUGS-1339.
=> doc(RHTAPWATCH-1105): Update multi-version doc

docs/modules/ROOT/pages/advanced-how-tos/_nav.adoc, docs/modules/ROOT/pages/advanced-how-tos/using-trusted-artifacts.adoc, docs/modules/ROOT/pages/how-tos/configuring/customizing-the-build.adoc
=> Add "Using Trusted Artifacts"

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/configuring/custom-tags.adoc, docs/modules/ROOT/pages/how-tos/configuring/entitlement_subscription.adoc
=> Migrate two documents from deprected docs.appstudio.io

docs/modules/ROOT/pages/glossary/index.adoc, docs/modules/ROOT/pages/how-tos/configuring/customizing-the-build.adoc, docs/modules/ROOT/pages/troubleshooting/index.adoc
[STONEBLD-2348](https://issues.redhat.com/browse/STONEBLD-2348)
Update outdated things, fix some problems
See the individual commits for details
=> Update build customization docs

docs/modules/ROOT/pages/how-tos/metadata/attestations.adoc
These are commands that I keep in my shell history and find myself frequently using to navigate around, and sharing the commands with others to do the same.
~~Here, I put them at the *top* of the doc in the hopes that it can be a quick reference for would-be power users.~~
=> Add some frequently used commands

docs/modules/ROOT/pages/advanced-how-tos/installing/enabling-builds.adoc, docs/modules/ROOT/pages/advanced-how-tos/installing/index.adoc, docs/modules/ROOT/pages/advanced-how-tos/managing-security-fix.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan-admission.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release.adoc, docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc, docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc, docs/modules/ROOT/pages/how-tos/configuring/customizing-the-build.adoc, docs/modules/ROOT/pages/how-tos/configuring/entitlement-subscription.adoc, docs/modules/ROOT/pages/how-tos/configuring/index.adoc, docs/modules/ROOT/pages/how-tos/configuring/reconfiguring-build-pipeline.adoc, docs/modules/ROOT/pages/how-tos/creating.adoc, docs/modules/ROOT/pages/how-tos/deleting.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/override-snapshots.adoc, docs/modules/ROOT/pages/troubleshooting/index.adoc
Changes include:
* Unification on use of `kubectl` in samples instead of `oc`
* Updating the component creation to include UI and CLI flow depending on what is configured
* Update to the installation enabling builds to add additional build configuration
* Add documentation for potential build pipelines
=> Rewrite onboarding flow

docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan-admission.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan.adoc
It means different things on the RP and RPA.
=> Document the nuance of the auto-release flag

docs/modules/ROOT/pages/advanced-how-tos/_nav.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/tenant-release-pipelines.adoc
I haven't had a chance to test this functionally. If you get a chance to try it out, please provide feedback here so we can clean it up and tune it.
=> Document how to use tenant release pipelines

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/configuring/dynamic-labels.adoc
In particular, how to introduce a monotonically increasing release label.
=> Document how to use dynamic labels

docs/modules/ROOT/pages/advanced-how-tos/releasing/tenant-release-pipelines.adoc, docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Problems discovered during the Konflux Onboarding Accelerator week in Brno
=> Miscellaneous fixes

docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
Updating all references to quay repo to reflect org change to konflux-ci.
=> feat(STONEINTG-946): migrate redhat-appstudio/konflux-test

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Document the feature of having multiple access tokens.
=> Update creating-secrets.adoc (multiple access tokens)

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc, docs/modules/ROOT/pages/troubleshooting/index.adoc
=> Add a reference to how to link secrets to SAs on manually created secrets

docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
=> document specifying your own renovate config for the nudging

docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc
Recent changes in project-controller lifted some of the documented limitations. This change removes those.
=> docs(KFLUXVNGD-36): project-controller out of order template changes

docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
This reverts commit ed7968427cd693389cb7f0b7b80aff93009272a5.
=> Revert "document specifying your own renovate config for the nudging"

docs/modules/ROOT/pages/how-tos/configuring/activation-keys-subscription.adoc
fixing some typos for the activation keys page
=> fix: some typos

docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
=> document specifying customized options for the nudging

docs/modules/ROOT/pages/getting-started/cli.adoc
Please verify that the new link is the correct one. It looks like the closest match, but I'm not the original author of this page.
=> Fix 404 link

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/third-parties/rapidast.adoc
add steps for using rapidast in an integration test
=> chore(stoneintg-1118): add guide for rapidast scan I.T.

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/third-parties/jenkins.adoc
This relies heavily on https://github.com/konflux-ci/tekton-integration-catalog/blob/main/docs/qe-available-tasks/trigger-jenkins-job.md
=> A how-to guide on testing with jenkins

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Align the steps with the flow the reader will follow.
=> In the Gitlab UI, this step comes first

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/configuring/labels-and-annotations.adoc
Documents https://github.com/konflux-ci/build-definitions/pull/1980
=> Add documentation about image annotations

docs/modules/ROOT/pages/how-tos/metadata/attestations.adoc
- Fix section level
- Fix annotation and URL in examples
=> Minor fixes

docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan.adoc
- Add documentation surrounding ReleaseGracePeriodDays in ReleasePlan.
=> chore(KONFLUX-7222): add docs about ReleaseGracePeriodDays

modules/ROOT/partials/custom-resources/konflux-component.adoc
=> Include optional git-provider annotations on component

modules/ROOT/pages/advanced-how-tos/testing-releasing-single-component.adoc
=> chore: note maintaining separate ITS for EC validations

CODEOWNERS
docs/ dir has been removed from paths
=> Codeowners: fix paths

.github/workflows/checks.yaml, .github/workflows/linters.yaml
Runs tests also in merge queue
=> Test on merge queue

CODEOWNERS
This is a follow up to https://github.com/konflux-ci/docs/pull/268 after we confirmed that it worked as expected.
=> Fix other codeowners references

modules/releasing/nav.adoc, modules/releasing/pages/adjusting-timeouts-resources.adoc
This commit adds information on how to modify the default timeouts and resources for PipelineRuns or specifc Tasks.
=> feat: add information about timeouts and resources

modules/patterns/pages/managing-multiple-versions.adoc
Now that this is in `patterns/` is appears as a "best practice" but I'm not sure that we want to advertise it that way.
=> Indicate that project controller is experimental

modules/patterns/nav.adoc, modules/patterns/pages/managing-monorepo-applications.adoc
* Add additional guidance for testing and releasing the monorepo pattern applications
=> feat(STONEINTG-1129): create user guide for monorepo users

modules/building/pages/creating.adoc
In order to properly function, Konflux needs to be able to push to branches for onbarding and renovate.
related: KFLUXSPRT-2555
=> Any branch protection rules need to be disabled for reserve branches

modules/patterns/nav.adoc, modules/patterns/pages/running-user-scripts-on-the-build-pipeline.adoc
Documents https://github.com/konflux-ci/build-definitions/pull/2044
=> Add guide about how to run scripts on the build pipeline to the patterns section

modules/testing/nav.adoc, modules/testing/pages/integration/canceling.adoc
Including documentation about canceling integration test pipelineruns.
=> doc(STONEINTG-1052): cancelling an integration test

modules/releasing/nav.adoc, modules/releasing/pages/using-collectors.adoc
This commit add a new section dedicated to the collectors feature.
=> feat(RELEASE-915): add collectors docs

modules/building/nav.adoc, modules/building/pages/build-binaries.adoc, modules/building/partials/konflux-example-binary-dockerfile.adoc
Adding some documentation about building binaries with Konflux
=> building binaries with Konflux docs

modules/mintmaker/pages/user.adoc
Fixes https://github.com/konflux-ci/docs/issues/336
=> Clarify mintmaker schedule

.vale.ini, .vale/styles/Konflux/GitLinks.yml, .vale/styles/config/vocabularies/konflux/accept.txt
These are a few things I came across while working on https://github.com/konflux-ci/docs/pull/341
=> Vale tweaks

modules/building/pages/creating-secrets.adoc, modules/building/pages/creating.adoc, modules/releasing/pages/adjusting-timeouts-resources.adoc, modules/releasing/pages/tenant-release-pipelines.adoc, modules/testing/pages/integration/rerunning.adoc, modules/troubleshooting/pages/registries.adoc, modules/troubleshooting/pages/releases.adoc
=> Update documentation about new service account model

modules/building/pages/component-nudges.adoc
=> document new renovate customize options for nudging

modules/testing/pages/integration/choosing-contexts.adoc
This PR is to clarify more on the usage of component_COMPONENT context
=> doc(STONEINTG-1149): add more details to contexts

modules/testing/pages/integration/creating.adoc
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
=> feat(STONEINTG-1142): update ITS creation doc

modules/testing/pages/integration/periodic-integration-tests.adoc
also include restartPolicy in yaml example of cronJob
=> fix(stoneintg-1243): incl info on roles and rolebindings

modules/patterns/pages/github-merge-queues.adoc
See:
* https://github.com/konflux-ci/integration-service/issues/1192
* https://github.com/konflux-ci/integration-service/pull/1197
=> chore: document how to prevent auto-release on push events

modules/end-to-end/pages/building-tekton-tasks.adoc
Add integration partial to tekton tasks onboarding
=> chore(): add integration partial

modules/releasing/pages/tenant-release-pipelines.adoc
Add note about community-catalog to Konflux docs.
=> feat(RELEASE-1493): add user documentation to community-catalog

modules/building/pages/creating-secrets.adoc
This is https://github.com/konflux-ci/docs/pull/232 with the review comments (mainly by @kleinffm) addressed.
Co-authored-by: @Jared-Sprague
=> Document how to use secrets in a Containerfile

antora-lunr-ui/partials/footer-content.hbs
My goal here was to link to the security.md file.
While here, I thought linking to the community readme would be good so that people can find the calendar and other things.
=> Link to security and community documents

modules/testing/pages/integration/third-parties/rapidast.adoc
~Draft for now, as link to the new example won't be ready until this merges:~
https://github.com/RedHatProductSecurity/rapidast/pull/401
EDIT: ready for merge 
Supports [PSSECAUT-1228](https://issues.redhat.com/browse/PSSECAUT-1228)
=> docs: Simplify rapidast docs and link to new exmaple

modules/mintmaker/pages/user.adoc
=> docs: Add instructions for providing registry secrets to MintMaker

modules/mintmaker/pages/user.adoc
=> Document automerge with OpenShift CI bot

modules/ROOT/partials/konflux-why-konflux.adoc
Add clarity regarding what Konflux is and how it can be used.
=> Update the Why Konflux introduction

modules/building/pages/entitlement-subscription.adoc
This PR has a few very minor edits. We need this pushed to see if the newly installed document enhancer works properly.
=> Small edits to fix a typo.
