konflux-ci/docs

docs/modules/ROOT/pages/how-tos/configuring/redundant-rebuilds.adoc
This is mostly a copy of an AppStudio guide. References to upgraded pipelines have been removed.
This content has been reviewed in a Gdoc (HACDOCS-922) and is ready to merge. Thank you.
=> Preventing redundant builds

docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
Purpose: The purpose of this PR is to develop the releasing an application content. I have copied the AppStudio content directly. We have to review and update it.
=> Added content for Creating a custom integration test for upstream

docs/modules/ROOT/pages/how-tos/configuring/configuration-as-code.adoc
Purpose: The purpose of this PR is to develop the releasing an application content. I have copied the AppStudio content directly. We have to review and update it.
=> Added Configuring Applications and Components as Code with Kustomize

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
Copied the general procedure from AppStudio docs.
Added a new section "Creating secrets for apps sourced from GitLab".
=> Creating secrets

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc, docs/modules/ROOT/pages/how-tos/configuring/hermetic-builds.adoc
STONEBLD-2339
The build-definitions repo has moved from github.com/redhat-appstudio to
github.com/konflux-ci. Update references accordingly.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
=> Update build-definitions references to new org

docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
It is possible for components to nudge or be nudged by components in another application altogether. The existing documentation did not make this clear. This change is an attempt to clarify that.
=> nudges: components referenced across applications

CONTRIBUTING.md, docs/modules/ROOT/pages/contribute/index.adoc
Reworked and extended the [AppStudio Contribute page](https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/contribute/).
Included the Mardown > AsciiDoc conversion option as requested in a JIRA issue.
=> Adding the contributing guide

docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
The text is being reviewed and will probably see a bit of changes.
=> Prefetching dependencies

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/configuring/rerunning.adoc, docs/modules/ROOT/pages/how-tos/testing/index.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/rerunning.adoc
Information on retriggering build pipelines was not migrated from the prior documentation. This is a migration of https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/configuring-builds/proc_retriggering_build_pipelines/
=> fix(KFLUXBUGS-1414) Migrate docs on retriggering build pipelines

docs/modules/ROOT/pages/advanced-how-tos/_nav.adoc, docs/modules/ROOT/pages/advanced-how-tos/building-olm.adoc, docs/modules/ROOT/pages/advanced-how-tos/releasing/maintaining-references-before-release.adoc
This topic relates to many other areas. While the motivating use cases were driven by OLM support, the actual topics likely fit closest to releasing ones especially since it is a requirement to have an RPA configured before it is possible.
This is a follow-up from #96.
=> Move how to maintain references before a release

docs/modules/ROOT/pages/how-tos/configuring/rerunning.adoc
This is currently the most reliable method of retriggering as some of the other methods have been hitting issues with all of the variables not being defined.
=> Document retriggering push events in git with PAC triggers

docs/modules/ROOT/pages/advanced-how-tos/releasing/maintaining-references-before-release.adoc
The first line was too low of a header so the rendering did not properly capture the page title resulting in `Untitled`.
=> Fix title for maintaining-references-before-release.adoc

docs/modules/ROOT/pages/how-tos/creating.adoc
Note on the `Creating applications and components` does not look correct.
Change the note so it looks like it should (please ignore the different IDE theme)
=> fix note syntax

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/configuring/customizing-the-build.adoc, docs/modules/ROOT/pages/how-tos/configuring/overriding-compute-resources.adoc
And discourage using buildah-*gb tasks
=> Document overriding compute resources

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/choosing-contexts.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
* Add the Choosing when to run certain Integration Tests page
* Document the example test-metadata task usage within the
integration testing pipelines
* Document the ability for users to provide custom annotations/labels
to their PaC definitions and access them in their integration tests
=> feat(STONEINTG-954): Document the integration test selection logic

docs/modules/ROOT/pages/advanced-how-tos/building-olm.adoc, docs/modules/ROOT/pages/how-tos/configuring/component-nudges.adoc
* Added notes for using the FBC fragment as a CatalogSource
* Added cautions to nudging to warn users about potential common issues
* Update the build-nudge-files annotation for clarity
=> Add and update notes for how-tos

docs/modules/ROOT/pages/advanced-how-tos/releasing/create-release-plan.adoc
change "serviceAccont" to "serviceAccount".
=> docs: fix typo on release plan example

docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
Replace YAML style commenting syntax in the examples scripts for creating integration tests with functional bash commenting.
=> docs: fix typos in creating integration test examples

docs/modules/ROOT/pages/advanced-how-tos/managing-compliance-with-ec/index.adoc, docs/modules/ROOT/pages/how-tos/configuring/custom-tags.adoc
These are deprecated, the new location is konflux-ci/tekton-catalog.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
=> Replace redhat-appstudio-tekton-catalog references

docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
This required adjusting language at the top of the document about what is supported.
=> Document how to configure rpm prefetch

docs/modules/ROOT/pages/how-tos/creating.adoc
Configuring components with immutable references like tags and commits can work to build artifacts but it doesn't work when trying to build new commits. Removing these options from the documentation.
=> Only suggest to use git branches for build references

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/adding.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/third-parties/testing-farm.adoc
Notably, this adds a `third-parties` section to the integration testing doc section. I expect we will expand this more over time, with jenkins, prow, and others.
This is a port of https://github.com/redhat-appstudio/docs.appstudio.io/pull/230 to the new repo.
=> Instructions for how to test with testing farm

docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc, docs/modules/ROOT/pages/how-tos/creating.adoc
In a recent commit [1], we changed the default ImageRepository name from '{namespace}/{application}/{component}' to '{namespace}/{component}'. The goal was to shorten image names while maintaining uniqueness (component names are unique within a namespace).
Update the templates accordingly to align with the default behavior.
[1]: https://github.com/konflux-ci/image-controller/commit/d9c695b343f8056d37b06a398f489bb4aa36d004
=> Remove app name from default ImageRepository name

docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc
I assume these parameters are not relevant for the example because they are not covered in the rest of the document.
@arewm ptal.
=> Remove unused parameters from custom integration test example.

docs/modules/ROOT/pages/how-tos/creating.adoc
Without this change, I was getting this error when creating that entity:
error: unable to decode "STDIN": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string
=> fix: error: unable to decode "STDIN": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string

docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
Cachi2's generic fetcher has recently emerged from the experimental phase and is now officially supported. This PR adds that documentation also to konflux docs.
(Note - the support comes with Cachi2's next release, which should happen today (2024-11-19), so this should be merged after that as to minimize user confusion)
=> Document Cachi2's generic fetcher

docs/modules/ROOT/pages/advanced-how-tos/managing-multiple-versions.adoc, docs/modules/ROOT/pages/how-tos/creating.adoc
In short: the common prefix of ImageRepository names is too long, which triggers https://issues.redhat.com/browse/SRVKP-6798
Drop the prefix.
=> Drop the common prefix of ImageRepository names

docs/modules/ROOT/pages/advanced-how-tos/releasing/tenant-release-pipelines.adoc
- release-service now expects `tenantPipeline` instead of `pipeline`, see https://github.com/konflux-ci/release-service/blob/e091a3b077f7b1743c17869a043b8fd8856c6112/api/v1alpha1/releaseplan_types.go#L49
- using `pipeline` results in an `unknown field error` which leads to user confusion
- change `pipeline` to `tenantPipeline` to reflect the release-service change
=> change pipeline to tenantPipeline

docs/modules/ROOT/pages/how-tos/testing/integration/creating.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/editing.adoc
* It is possible to set custom pipeline timeouts via annotations
=> doc: custom timeout annotations for integration tests

docs/modules/ROOT/pages/how-tos/configuring/activation-keys-subscription.adoc
This makes minor adjustments to some newly added documentation about
generating lock files, which is important for pre-fetching RPMs for
hermetic builds.
- Use consistent vertical spacing
- Use consistent punctuation in section titles
- Add in a step for skopeo login
- Fix `ocp-clients` RPM name
- Use literals for file names and tools
- Add a note about installing rpm-lockfile-prototype versions
=> Update directions for creating lock files

docs/modules/ROOT/pages/how-tos/testing/integration/adding.adoc
Prior to this change the documentation for adding integration tests was github-specific.  This change makes the documentation more general to avoid confusion for users adding components and integration tests from Gitlab.
=> chore: generalize github references

.github/workflows/linters.yaml, .gitignore, .vale.ini, .vale/styles/config/vocabularies/konflux/accept.txt
This patch introduces [Vale](https://vale.sh/docs) as a writing style linter, and configures it using Red Hat's [styles](https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/introduction/).
It also sets up a corresponding Github Action to run Vale during the CI. If any of the lines introduced by the PR causes an error level linting message, the CI will fail.
=> Add Vale linter to CI

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
The default secret name for the task is `snyk-secret`: https://github.com/konflux-ci/build-definitions/blob/9f209df8c12e8b321e63b77b5c91cb1523080a59/task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml#L49-L51
Therefore, in order to make it work out of the box, that should probably be the name that we suggest for users to configure.
=> Change the name of the snyk secret to create

docs/modules/ROOT/pages/advanced-how-tos/releasing/tenant-release-pipelines.adoc
The pipelineRef in the tenant pipeline never really made much sense. It suggested using a managed pipeline, which would not work (and many users made this mistake). This updates the example to something that should be more obviously an example and not a real pipeline.
We also moved the pipeline definitions in release-service-catalog, so the old reference won't even exist going forward. That is another reason to change it.
If a working tenant pipeline is created, we can update the docs to use that as the example.
=> docs(RELEASE-1320): update tenant pipeline example pipelineRef

docs/modules/ROOT/pages/how-tos/testing/build/snyk.adoc
Adding documentation showing users how to exclude file paths from the Snyk scans.
=> Added documentation for ignoring file paths in Snyk scans

docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
The asterisk prevented jumping to the linked section.
=> Fix jump link to rpm prefetching guide

docs/modules/ROOT/pages/how-tos/configuring/rerunning.adoc
To re-run the push pipeline for a commit on a non-default branch, the user needs `/retest branch:<branch-name>`
=> Document /retest branch:<branch-name>

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc, docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
A user recently encountered issues with prefetching Go modules from private repos. We figured out that this requires `.netrc`
=> Document that private Go modules need .netrc

.gitignore, .vale.ini, .vale/styles/Konflux/UpstreamLinks.yml, docs/modules/ROOT/pages/how-tos/configuring/hermetic-builds.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/choosing-contexts.adoc
Not using xref will prevent proper generation of donwstream docs.
It also makes harder to check existence of referenced content.
=> Ensure that xref is used to refence doc

docs/modules/ROOT/pages/how-tos/configuring/prefetching-dependencies.adoc
While using the rpm-lockfile-prototype command when building a multi-arch container, all architectures must be specified using the `--arch` command-line option, otherwise the build task will fail.
=> Add arch explanation to rpms.in.yaml

docs/modules/ROOT/pages/troubleshooting/index.adoc
Add a documentation block guiding users on how to update tekton bundle references manually without waiting for renovate.
=> Document manual task update

docs/modules/ROOT/pages/how-tos/configuring/creating-secrets.adoc
We added a tekton task as an example how user can use the created secrets 
within a build or integration pipeline 
[KONFLUX-5917](https://issues.redhat.com/browse/KONFLUX-5917)
=> fix(Konflux 5917):  add an example how user can use a secret in pipeline 

docs/modules/ROOT/pages/troubleshooting/index.adoc
Without the `-e` flag for sed, the command will fail on a mac with an `undefined label` error. Also changed the script name to be consistent throughout.
=> Enable task update automation to work on a mac

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/accessing-private-repositories.adoc
There has been lots of user confusion about how to access pipelines in private repos from the Integration Test Scenarios.  This document outlines the process on how to do it and links to the Tekton Git Resolver documentation, which contains a bit more information on how Git Resolvers work
=> doc(konflux-5673): document process for accessing private repo

docs/modules/ROOT/pages/how-tos/_nav.adoc, docs/modules/ROOT/pages/how-tos/testing/integration/periodic-integration-tests.adoc
This Pull Request create documentation about how to run Periodic Integration tests using Kubernetes Cronjob.
Jira issue: https://issues.redhat.com/browse/KFLUXDP-198
=> feat: Create documentation to help user to schedule periodic Integration tests

docs/modules/ROOT/pages/how-tos/testing/integration/third-parties/testing-farm.adoc
Testing Farm Team needed to move the repo because the ArtifactsHub doesn't support subgroups in GitLab
=> Change testing farm docs link

package-lock.json, package.json
- Update `package.json` to keep npm package name consistent.
- Update `package-lock.json` from npm install.
=> fix: Override npm Package Name

docs/modules/ROOT/pages/how-tos/configuring/configuration-as-code.adoc, docs/modules/ROOT/pages/how-tos/creating.adoc, docs/modules/ROOT/partials/custom-resources/konflux-application.adoc, docs/modules/ROOT/partials/custom-resources/konflux-component.adoc, docs/modules/ROOT/partials/custom-resources/konflux-imagerepository.adoc
This will help to ensure that CR definitions are consistent across multiple pages. It will also allow other documentation pages to update the CRs with any additional requirement that those systems might want to impose.
=> Move component, application, imagerepository CRs into partials

modules/ROOT/pages/end-to-end/_nav.adoc
Confirmed locally - this is not necessary.
=> Remove block continuation from nav partial

modules/ROOT/pages/building/prefetching-dependencies.adoc, modules/ROOT/partials/building/konflux-example-prefetch-rpm-containerfile.adoc, modules/ROOT/partials/building/konflux-example-prefetch-rpm-copy-repo.adoc, modules/ROOT/partials/building/konflux-example-prefetch-rpm-execute.adoc, modules/ROOT/partials/building/konflux-example-prefetch-rpm-lockfile.adoc, modules/ROOT/partials/building/konflux-example-prefetch-rpm-rpms_in_yaml.adoc
Allow to replace examples in downstream
=> Prefetch RPM: use partials in examples

modules/ROOT/pages/getting-started.adoc, modules/building/pages/configuration-as-code.adoc, modules/building/pages/creating-secrets.adoc, modules/building/pages/creating.adoc, modules/building/pages/prefetching-dependencies.adoc, modules/end-to-end/nav.adoc, modules/patterns/pages/git-submodules.adoc, modules/reference/pages/sample-repositories.adoc
During the refactoring done in xxx, some of the includes were incorrectly written as "include:" instead of "include::". Also, by moving the partials to their respective modules, the previous folder they were placed at is no longer part of the path.
See more info a the official Antora [docs](https://docs.antora.org/antora/latest/page/include-a-partial/).
=> Fix incorrect partial includes

CODEOWNERS
I want to merge this and confirm that it does what we expect for https://github.com/konflux-ci/docs/pull/231
If it does, then lets fix the other codeowners lines in the same way.
=> Fix codeowners for release team

modules/releasing/pages/tenant-release-pipelines.adoc
The documentation for tenant pipelines was quite inaccurate. This commit addresses some gaps and add examples to show users how to create a tenant pipeline.
=> fix: update tenant pipelines documentation

antora.yml, modules/mintmaker/nav.adoc, modules/mintmaker/pages/rpm-lockfile.adoc, modules/mintmaker/pages/support.adoc, modules/mintmaker/pages/user.adoc
This is the whole documentation on dependency management / MintMaker from internal docs. I removed any reference to internal stuff, like Slack channels or Jira issues, that would not be accessible from the public web.
=> Move MintMaker documentation upstream

modules/building/pages/prefetching-dependencies.adoc
These were incorrectly added in a recent [fix](https://github.com/konflux-ci/docs/pull/267) of partials.
=> Fix includes that have three colons in the prefetch docs

modules/building/pages/labels-and-annotations.adoc
I realized today while checking the new structure I made two mistakes while extending the labels docs with annotations.
First of all, I forgot to change the page title. I changed the section name on the ToC, but not the name on the table itself.
The second one is about the callouts on the code. The callout on the code block are numbered `1` and `2` for labels and annotations but then there is a single explanation for both of them
=> Fix title and callouts on labels and annotations page

modules/patterns/pages/managing-monorepo-applications.adoc
* Add a section on building monorepo applications with a link to preventing redundant rebuilds
=> doc: add monorepo building guidance

modules/building/pages/customizing-the-build.adoc
Simply adding the slack-webhook-notification task as suggested in the original doc will fail with a message like this:
```Tekton Controller has reported this error: admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: pipeline tasks can not refer to execution status of any other pipeline task or aggregate status of tasks: spec.pipelineSpec.tasks[2].when[0]```
A pipeline that fans out needs to rendezvous and aggregate the status *at the end* to be sure it can catch any failure along the line.
=> Add `finally` nuance to slack-webhook-notification

modules/installing/nav.adoc, modules/installing/pages/enabling-builds.adoc, modules/installing/pages/github-app.adoc
Some users encountered difficulties understading/trusting what GitHub App is during UX testing
This page should clarify their concerns
Creating a new subpage should make it easier for users to navigate and could be used later in the UI 
Users had concerns about:
- what the app does
- where is it installed
- whether it is a legitimate request from Red Hat
=> Add GitHub App page

modules/building/pages/creating-secrets.adoc, modules/troubleshooting/nav.adoc, modules/troubleshooting/pages/builds.adoc, modules/troubleshooting/pages/index.adoc, modules/troubleshooting/pages/registries.adoc, modules/troubleshooting/pages/releases.adoc, modules/troubleshooting/partials/konflux-releases.adoc
I organized the troubleshooting doc into three sections: build, release, and registries and made partials available for each section to allow downstream customization.
=> Reorganize troubleshooting to include partials

modules/building/pages/prefetching-dependencies.adoc
For users new to prefetch/konflux, it might no be obvious to them to that the`prefetch-input`needs to be set here.
To update this section: https://konflux-ci.dev/docs/building/prefetching-dependencies/#enabling-prefetch-builds-for-rpm
=> Update rpm prefetch docs

modules/mintmaker/pages/rpm-lockfile.adoc
Add documentation note explaining how to run rpm-lockfile-prototype locally, when repo config has some variables.
=> Add note about running rpm-lockfile-prototype locally

modules/building/partials/custom-resources/konflux-application.adoc, modules/building/partials/custom-resources/konflux-component.adoc, modules/building/partials/custom-resources/konflux-imagerepository.adoc
When moving the custom resources to partials, we had the format following the content for the creating page which was in a list. Maintining the indentation continuity broke the rendering when there was no list, however (i.e. configuration as code) pages. Instead of having a `+` to restore the indentation, we can just delete the newline. This will ensure proper context in both types of partial inclusions.
resolves: #315
=> fix(315): Restore numbering for custom resource partials

modules/testing/nav.adoc, modules/testing/pages/integration/snapshots/index.adoc, modules/testing/pages/integration/snapshots/working-with-snapshots.adoc
We just jump into working with Snapshots but we don't provide enough context about Snapshots and what they mean. We can improve that with a summary index.adoc.
Resolves: STONEINTG-1204
=> fix: Document Snapshot introductory material

antora-lunr-ui/partials/header-content.hbs, antora-playbook.yml
This change will affect the name that is displayed in the browser tab.
Since the added "Konflux" will be redundant with the logo that is displayed in the site's header (making it show as "Konflux Konflux Documentation"), we need to disassociate the rendering of the header with the site's configured title.
=> Change the website title to "Konflux Documentation"

modules/building/pages/creating-secrets.adoc
Also mention what the key should be.
For details see the default param value here:
https://github.com/konflux-ci/build-definitions/blob/896d2925db3e75087ded6b6cffac92a3324f5fe4/task/sast-snyk-check/0.4/sast-snyk-check.yaml#L23-L25
And how the key is used:
https://github.com/konflux-ci/build-definitions/blob/896d2925db3e75087ded6b6cffac92a3324f5fe4/task/sast-snyk-check/0.4/sast-snyk-check.yaml#L139-L143
The incorrect docs were reported in the slack thread referenced by:
https://issues.redhat.com/browse/KFLUXSPRT-3153
=> Update the suggested snyk secret name

modules/building/pages/activation-keys-subscription.adoc
The `rpm-lockfile-prototype` tool does not need to be executed in the same container environment as the build. The content of the `.repo` files rather than the tool execution environment are what is important.
=> clarify rpm-lockfile-prototype execution env

modules/building/pages/creating-secrets.adoc
Restrictive push rules in a Gitlab project can cause Konflux to fail to push to a repository.
=> Gitlab PAT: add note about project push rules

modules/building/pages/creating.adoc
orphaned imageRepository and UI failing with imageRepository already exists
=> Add note about removing component right after creation resulting in

modules/building/pages/customizing-the-build.adoc, modules/patterns/nav.adoc, modules/patterns/pages/slack-notifications.adoc
The purpose is to highlight it in search results, since people ask about it so much.
=> feat(KONFLUX-277) move slack notifications to its own page

modules/patterns/pages/centralize-pipeline-definitions.adoc
When using eval-all, the output is a one-line json string. We don't want that nor do we need to use eval-all. This generate a properly formatted extracted pipeline definition.
=> Improve yq helper script

modules/testing/pages/integration/creating.adoc
Description and guide of newly added parameter **resourceKind** into integration-service ecosystem.
Example of how users can set their integration test scenario to customize parameters for pipelineRun instead of pipeline.
=> doc(STONEINTG-1206): pipelinerun support for ITS

modules/testing/pages/build/index.adoc, modules/testing/pages/integration/standardized-outputs.adoc
Clair scan detects blocking high CVE vulnerabilities that are not included in the SCAN_OUTPUT within Konflux. This PR adds a note explaining that only advisories associated with RHSAs will be reported.
=> fix(KONFLUX-7679): clair scan vulns missing from SCAN_OUTPUT

modules/building/pages/prefetching-dependencies.adoc
After spending some time looking for my assets using the generic fetcher I found them stored under `/cachi2/output/deps/generic/`. 
I figured this out through trial and error after looking at my pipeline logs and seeing this line:
```
RUN . /cachi2/cachi2.env
```
I tried combing through the docs but I may have missed it. Hopefully this saves some time for someone else too.
=> chore(docs): add section on accessing assets retrieved by generic fetcher

modules/releasing/pages/tenant-release-pipelines.adoc
Users can't bind to get/patch CR Status, so remove that from the example Role in the tenant release pipeline page.
=> fix: update tenant pipeline example role

modules/building/pages/prefetching-dependencies.adoc
The section about pip in the prefetching dependencies was very outdated. There is a new officially supported tool to resolve pip build dependencies, which is now properly referenced there.
I also took the opportunity to clarify the two approaches for prefetching pip dependencies: only sdists (to build from source) or also allowing the prefetching of pre-compiled wheels.
=> Hermeto/Cachi2: recomend the use of pybuild-deps for resolving pip build deps

modules/patterns/pages/gitops-for-manual-releases.adoc, modules/patterns/partials/konflux-gitops-for-manual-releases-head-note.adoc
Example of downstream usage: https://gitlab.cee.redhat.com/konflux/docs/users/-/merge_requests/382
=> Create space for a partial about gitops releases

modules/troubleshooting/pages/builds.adoc
Updated the update-tekton-task-bundles.sh script so that it  works:
- Two dots instead of an ellipsis in yp '..
- Removed double quotes in several places
=> Updated the update-tekton-task-bundles.sh script

modules/end-to-end/pages/building-tekton-tasks.adoc, modules/reference/pages/kube-apis/release-service.adoc, modules/releasing/pages/adjusting-timeouts-resources.adoc, modules/releasing/pages/create-release-plan-admission.adoc
This commit updates the documentation to deprecate the `auto-release` label on ReleasePlanAdmissions (unchanged on ReleasePlans) with the `block-releases` label. They work the same, but opposite, so auto-release true works the same as block-releases false.
=> docs(RELEASE-1352): replace `auto-release` with `block-releases` label

modules/releasing/pages/create-release.adoc, modules/releasing/partials/example-manual-release.adoc
Document how to re-trigger a Release pipeline, which requires developers to create a new instance of a Release object using the same `spec` field values. Caution must be taken as release pipelines are not guaranteed to be idempotent.
See [KONFLUX-9511](https://issues.redhat.com/browse/KONFLUX-9511)
=> doc: Re-trigger a Release

hack/gen-api-docs.sh, modules/reference/nav.adoc, modules/reference/pages/kube-apis/index.adoc, modules/reference/pages/kube-apis/project-controller.adoc
CRDs are cloned and API documentation is generated for Project Controller
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-440
=> docs: Add Project Controller to gen-api-docs

modules/mintmaker/pages/user.adoc
Expand documentation to mention that renovate.json can be placed in multiple locations as specified in Renovate documentation, not just the top-level directory.
=> docs(mintmaker): clarify Renovate configuration file locations

modules/ROOT/nav.adoc, modules/ROOT/pages/share-with-community.adoc, modules/ROOT/partials/konflux-share-community-cli-setup.adoc
Konflux tenant admins can now give visibility to each authenticated user to their namespaces.
Signed-off-by: Francesco Ilario <filario@redhat.com>
=> add documentation for Public-Viewer

modules/building/pages/creating-secrets.adoc, modules/testing/nav.adoc, modules/testing/pages/integration/accessing-private-repositories.adoc
Guide for accessing image pull secrets in integration pipelines
* Add information about `konflux-integration-runner` service account
* Add information about linking image pull secrets to service account
=> docs(STONEINTG-1215): add guide for accessing private image repositories

modules/reference/pages/sample-repositories.adoc
- The original sample repo is now being used for testing purposes and is locked down as a private repo.
- The new repo is a copy of the sample one.
=> update the location of the multi-arch example

modules/building/pages/prefetching-dependencies.adoc, modules/building/partials/konflux-example-prefetch-rpm-dnf-repo-options.adoc, modules/building/partials/konflux-prefetch-hermeto-note.adoc
- add links to upstream walkthroughs for each supported package manager (e.g. [gomod](https://hermetoproject.github.io/hermeto/gomod/#example))
- update existing links to point to upstream Hermeto [docs site](https://hermetoproject.github.io/hermeto/usage)
- note that there are important differences between pipeline invocation vs command-line tool
- replace all references to "Cachi2" with "Hermeto"
-----
- closes #412
- obviates #388 (sorry, Bruno!) - the links to the recently launched github.io site would've needed to be added anyway
=> docs(prefetch): fix up examples by linking to full walkthroughs in Hermeto docs

modules/metadata/pages/discover.adoc, modules/metadata/pages/sboms.adoc
The upstream cosign devs have moved the install instructions to a new
location. Update the link to reflect this change.
=> fix cosign installation URL

modules/releasing/pages/create-release-plan.adoc
The auto-release label in the ReleasePlan object now supports cel expressions for more granular release creation.  This commit documents those changes.
=> add documentation for cel-based auto-release logic
